jabberd2: util/access.c File Reference
access.c File Reference
#include "util.h"
Functions
access_t access_new (int order)
void access_free (access_t access)
static int _access_calc_netsize (const char *mask, int defaultsize)
static void _access_unmap_v4 (struct sockaddr_in6 *src, struct sockaddr_in *dst)
convert a IPv6 mapped IPv4 address to a real IPv4 address
static int _access_check_match (struct sockaddr_storage *ip_1, struct sockaddr_storage *ip_2, int netsize)
check if two ip addresses are within the same subnet
int access_allow (access_t access, char *ip, char *mask)
int access_deny (access_t access, char *ip, char *mask)
int access_check (access_t access, char *ip)
Function Documentation
access_t access_new (int order)
Definition at line 25 of file access.c.
References access_st::order.
Referenced by _c2s_config_expand(), and _router_config_expand().
void access_free (access_t access)
Definition at line 34 of file access.c.
References access_st::allow, and access_st::deny.
Referenced by JABBER_MAIN().
static int _access_calc_netsize (const char * mask, int defaultsize) static
Definition at line 41 of file access.c.
References j_atoi().
Referenced by access_allow(), and access_deny().
static void _access_unmap_v4 (struct sockaddr_in6 * src, struct sockaddr_in * dst) static
convert a IPv6 mapped IPv4 address to a real IPv4 address
Definition at line 70 of file access.c.
References in6_addr::s6_addr, and sockaddr_in6::sin6_addr.
Referenced by _access_check_match().
static int _access_check_match (struct sockaddr_storage * ip_1, struct sockaddr_storage * ip_2, int netsize) static
check if two ip addresses are within the same subnet
Definition at line 78 of file access.c.
References _access_unmap_v4(), AF_INET6, IN6_IS_ADDR_V4MAPPED, in6_addr::s6_addr, sockaddr_in6::sin6_addr, and sockaddr_storage::ss_family.
Referenced by access_check().
int access_allow (access_t access, char * ip, char * mask)
Definition at line 163 of file access.c.
References _access_calc_netsize(), access_st::allow, access_rule_st::ip, j_inet_pton(), access_rule_st::mask, access_st::nallow, and sockaddr_storage::ss_family.
Referenced by _c2s_config_expand(), and _router_config_expand().
int access_deny (access_t access, char * ip, char * mask)
Definition at line 183 of file access.c.
References _access_calc_netsize(), access_st::deny, access_rule_st::ip, j_inet_pton(), access_rule_st::mask, access_st::ndeny, and sockaddr_storage::ss_family.
Referenced by _c2s_config_expand(), and _router_config_expand().
int access_check (access_t access, char * ip)
Definition at line 203 of file access.c.
References _access_check_match(), access_st::allow, access_st::deny, j_inet_pton(), access_st::nallow, access_st::ndeny, and access_st::order.
Referenced by _c2s_client_accept_check(), and _router_accept_check().