jabberd2: sx/address.c File Reference
address.c File Reference
#include "sx.h"
Functions
static void _sx_address_features (sx_t s, sx_plugin_t p, nad_t nad)
sx features callback
int sx_address_init (sx_env_t env, sx_plugin_t p, va_list args)
args: none
Function Documentation
static void _sx_address_features (sx_t s, sx_plugin_t p, nad_t nad) static
sx features callback
Definition at line 27 of file address.c.
References _sx_debug, _sx_st::ip, nad_add_namespace(), nad_append_cdata(), nad_append_elem(), _sx_st::state, state_OPEN, uri_ADDRESS_FEATURE, and ZONE.
Referenced by sx_address_init().
int sx_address_init (sx_env_t env, sx_plugin_t p, va_list args)
args: none
Definition at line 42 of file address.c.
References _sx_address_features(), _sx_plugin_st::features, log_debug, and ZONE.
Referenced by JABBER_MAIN().