jabberd2: c2s/authreg.c File Reference
authreg.c File Reference
#include "c2s.h"
#include <stringprep.h>
#include <dlfcn.h>
Data Structures
struct _authreg_error_st
Typedefs
typedef struct _authreg_error_st * authreg_error_t
Functions
authreg_t authreg_init (c2s_t c2s, char *name)
get a handle for the named module
void authreg_free (authreg_t ar)
shutdown the authreg system
static void _authreg_auth_log (c2s_t c2s, sess_t sess, char *method, char *username, char *resource, int success)
auth logger
static void _authreg_auth_get (c2s_t c2s, sess_t sess, nad_t nad)
auth get handler
static void _authreg_auth_set (c2s_t c2s, sess_t sess, nad_t nad)
auth set handler
static void _authreg_register_get (c2s_t c2s, sess_t sess, nad_t nad)
register get handler
static void _authreg_register_set (c2s_t c2s, sess_t sess, nad_t nad)
register set handler
int authreg_process (c2s_t c2s, sess_t sess, nad_t nad)
processor for iq:auth and iq:register packets return 0 if handled, 1 if not handled
Typedef Documentation
typedef struct _authreg_error_st * authreg_error_t
Function Documentation
authreg_t authreg_init (c2s_t c2s, char * name)
get a handle for the named module
get a handle for a single module
Definition at line 40 of file authreg.c.
References authreg_free(), authreg_st::c2s, c2s_st::config, config_get_one(), c2s_st::log, log_debug, log_write(), PATH_MAX, authreg_st::user_exists, and ZONE.
Referenced by JABBER_MAIN().
void authreg_free (authreg_t ar)
shutdown the authreg system
shut down
Definition at line 115 of file authreg.c.
References authreg_st::free.
Referenced by authreg_init(), and JABBER_MAIN().
static void _authreg_auth_log (c2s_t c2s, sess_t sess, char * method, char * username, char * resource, int success) inline static
auth logger
Definition at line 123 of file authreg.c.
References _sx_st::compressed, sess_st::host, _sx_st::ip, c2s_st::log, log_write(), _sx_st::port, host_st::realm, sess_st::s, _sx_st::ssf, and _sx_st::tag.
Referenced by _authreg_auth_set().
static void _authreg_auth_get (c2s_t c2s, sess_t sess, nad_t nad) static
auth get handler
Definition at line 133 of file authreg.c.
References sess_st::active, c2s_st::ar, AR_MECH_TRAD_DIGEST, AR_MECH_TRAD_PLAIN, c2s_st::ar_mechanisms, c2s_st::ar_ssl_mechanisms, authreg_st::check_password, authreg_st::get_password, sess_st::host, log_debug, nad_add_namespace(), nad_append_attr(), nad_append_cdata(), nad_append_elem(), NAD_AVAL, NAD_AVAL_L, NAD_CDATA, NAD_CDATA_L, nad_find_attr(), nad_find_elem(), nad_find_scoped_namespace(), nad_free(), nad_new(), host_st::realm, sess_st::s, _sx_st::ssf, stanza_err_BAD_REQUEST, stanza_err_FORBIDDEN, stanza_err_JID_MALFORMED, stanza_err_NOT_ALLOWED, stanza_err_OLD_UNAUTH, stanza_error(), stanza_tofrom(), sx_nad_write, uri_AUTH, uri_CLIENT, authreg_st::user_exists, and ZONE.
Referenced by authreg_process().
static void _authreg_auth_set (c2s_t c2s, sess_t sess, nad_t nad) static
auth set handler
Definition at line 219 of file authreg.c.
References _authreg_auth_log(), sess_st::active, c2s_st::ar, AR_MECH_TRAD_DIGEST, AR_MECH_TRAD_PLAIN, c2s_st::ar_mechanisms, c2s_st::ar_ssl_mechanisms, sess_st::c2s, bres_st::c2s_id, authreg_st::check_password, jid_st::domain, authreg_st::get_password, sess_st::host, _sx_st::id, bres_st::jid, jid_full(), jid_new(), jid_reset_components(), c2s_st::log, log_debug, log_write(), nad_add_namespace(), nad_append_elem(), NAD_AVAL, NAD_AVAL_L, NAD_CDATA, NAD_CDATA_L, nad_find_attr(), nad_find_elem(), nad_find_scoped_namespace(), nad_free(), nad_new(), nad_set_attr(), host_st::realm, _sx_st::req_to, sess_st::resources, sess_st::result, sess_st::s, shahash_r(), sm_start(), _sx_st::ssf, stanza_err_BAD_REQUEST, stanza_err_FORBIDDEN, stanza_err_JID_MALFORMED, stanza_err_NOT_ALLOWED, stanza_err_OLD_UNAUTH, stanza_error(), stanza_tofrom(), sx_nad_write, _sx_st::tag, uri_AUTH, uri_CLIENT, authreg_st::user_exists, and ZONE.
Referenced by authreg_process().
static void _authreg_register_get (c2s_t c2s, sess_t sess, nad_t nad) static
register get handler
Definition at line 383 of file authreg.c.
References sess_st::active, c2s_st::ar, host_st::ar_register_enable, host_st::ar_register_instructions, host_st::ar_register_oob, authreg_st::create_user, sess_st::host, nad_add_namespace(), nad_append_attr(), nad_append_cdata(), nad_append_elem(), NAD_AVAL, NAD_AVAL_L, nad_find_attr(), nad_free(), nad_new(), sess_st::s, authreg_st::set_password, stanza_err_NOT_ALLOWED, stanza_error(), stanza_tofrom(), sx_nad_write, uri_CLIENT, uri_OOB, and uri_REGISTER.
Referenced by authreg_process().
static void _authreg_register_set (c2s_t c2s, sess_t sess, nad_t nad) static
register set handler
Definition at line 434 of file authreg.c.
References sess_st::active, c2s_st::ar, host_st::ar_register_enable, host_st::ar_register_password, bres_st::c2s_id, authreg_st::create_user, authreg_st::delete_user, jid_st::domain, sess_st::host, bres_st::jid, jid_full(), jid_new(), jid_reset_components(), jid_user(), c2s_st::log, log_debug, log_write(), nad_add_namespace(), nad_append_elem(), NAD_AVAL, NAD_AVAL_L, NAD_CDATA, NAD_CDATA_L, nad_find_attr(), nad_find_elem(), nad_find_scoped_namespace(), nad_free(), nad_new(), nad_set_attr(), jid_st::node, host_st::realm, _sx_st::req_to, jid_st::resource, sess_st::resources, sess_st::result, sess_st::s, authreg_st::set_password, sm_create(), sm_delete(), stanza_err_BAD_REQUEST, stanza_err_CONFLICT, stanza_err_INTERNAL_SERVER_ERROR, stanza_err_JID_MALFORMED, stanza_err_NOT_ALLOWED, stanza_err_OLD_UNAUTH, stanza_error(), stanza_tofrom(), sx_nad_write, _sx_st::tag, uri_CLIENT, uri_REGISTER, authreg_st::user_exists, and ZONE.
Referenced by authreg_process().
int authreg_process (c2s_t c2s, sess_t sess, nad_t nad)
processor for iq:auth and iq:register packets return 0 if handled, 1 if not handled
the main authreg processor
Definition at line 626 of file authreg.c.
References _authreg_auth_get(), _authreg_auth_set(), _authreg_register_get(), _authreg_register_set(), log_debug, NAD_AVAL, NAD_AVAL_L, NAD_ENAME, NAD_ENAME_L, nad_find_attr(), nad_find_elem(), nad_find_scoped_namespace(), _sx_st::req_to, sess_st::s, sess_st::sasl_authd, stanza_err_BAD_REQUEST, stanza_err_NOT_ALLOWED, stanza_error(), stanza_tofrom(), sx_nad_write, uri_AUTH, uri_REGISTER, and ZONE.
Referenced by _c2s_client_sx_callback().