jabberd2: sx/io.c File Reference
io.c File Reference
#include "sx.h"
Functions
void _sx_process_read (sx_t s, sx_buf_t buf)
handler for read data
int sx_can_read (sx_t s)
we can read
static int _sx_get_pending_write (sx_t s)
we can write
int sx_can_write (sx_t s)
int _sx_nad_write (sx_t s, nad_t nad, int elem)
send a new nad out
void sx_nad_write_elem (sx_t s, nad_t nad, int elem)
app version
int _sx_raw_write (sx_t s, char *buf, int len)
send raw data out
void sx_raw_write (sx_t s, char *buf, int len)
app version
void _sx_close (sx_t s)
close a stream
void sx_close (sx_t s)
void sx_kill (sx_t s)
Function Documentation
void _sx_process_read (sx_t s, sx_buf_t buf)
handler for read data
processor for incoming wire data
Definition at line 24 of file io.c.
References _sx_buffer_free(), _sx_buffer_new(), _sx_chain_nad_read(), _sx_close(), _sx_debug, _sx_error(), _sx_event, _sx_gen_error, _sx_state, _sx_buf_st::data, _sx_st::depth, _sx_st::env, event_ERROR, event_PACKET, _sx_st::expat, _sx_st::fail, jqueue_pull(), jqueue_push(), _sx_buf_st::len, NAD_CDATA, NAD_CDATA_L, NAD_ENAME, NAD_ENAME_L, NAD_ENS, nad_find_elem(), nad_find_scoped_namespace(), nad_free(), NAD_NURI, NAD_NURI_L, nad_print(), _sx_env_st::nplugins, _sx_env_st::plugins, _sx_plugin_st::process, _sx_st::rbytes, _sx_st::rbytesmax, _sx_st::rnadq, _sx_st::state, state_CLOSING, state_STREAM, state_STREAM_SENT, stream_err_POLICY_VIOLATION, stream_err_XML_NOT_WELL_FORMED, SX_ERR_STREAM, SX_ERR_XML_PARSE, uri_STREAM_ERR, uri_STREAMS, _sx_st::want_write, _sx_st::wbufq, and ZONE.
Referenced by _sx_server_notify_header(), and sx_can_read().
int sx_can_read (sx_t s)
we can read
Definition at line 181 of file io.c.
References _sx_buffer_free(), _sx_buffer_new(), _sx_chain_io_read(), _sx_debug, _sx_event, _sx_process_read(), _sx_state, _sx_buf_st::data, event_CLOSED, event_READ, event_WANT_WRITE, _sx_buf_st::len, _sx_buf_st::notify, _sx_buf_st::notify_arg, _sx_st::state, state_CLOSED, state_CLOSING, _sx_st::tag, _sx_st::want_read, _sx_st::want_write, and ZONE.
Referenced by _c2s_client_mio_callback(), _c2s_time_checks(), _out_mio_callback(), c2s_router_mio_callback(), in_mio_callback(), router_mio_callback(), s2s_router_mio_callback(), and sm_mio_callback().
static int _sx_get_pending_write (sx_t s) static
we can write
Definition at line 261 of file io.c.
References _sx_buffer_free(), _sx_buffer_new(), _sx_chain_io_write(), _sx_debug, _sx_buf_st::data, _jqueue_st::front, jqueue_pull(), jqueue_push(), jqueue_size(), _sx_buf_st::len, _sx_buf_st::notify, _sx_buf_st::notify_arg, _jqueue_node_st::priority, _sx_st::want_read, _sx_st::want_write, _sx_st::wbufpending, _sx_st::wbufq, and ZONE.
Referenced by sx_can_write().
int sx_can_write (sx_t s)
Definition at line 318 of file io.c.
References _sx_buffer_free(), _sx_debug, _sx_event, _sx_get_pending_write(), _sx_state, _sx_buf_st::data, event_CLOSED, event_WANT_READ, event_WRITE, _sx_buf_st::len, _sx_buf_st::notify, _sx_buf_st::notify_arg, _sx_st::state, state_CLOSED, state_CLOSING, sx_kill(), _sx_st::tag, _sx_st::want_read, _sx_st::want_write, _sx_st::wbufpending, and ZONE.
Referenced by _c2s_client_mio_callback(), _out_mio_callback(), c2s_router_mio_callback(), in_mio_callback(), router_mio_callback(), s2s_router_mio_callback(), and sm_mio_callback().
int _sx_nad_write (sx_t s, nad_t nad, int elem)
send a new nad out
sending a nad (internal)
Definition at line 388 of file io.c.
References _sx_buffer_new(), _sx_chain_nad_write(), _sx_debug, jqueue_push(), log_debug, nad_free(), nad_print(), _sx_st::state, state_CLOSING, _sx_st::want_write, _sx_st::wbufq, and ZONE.
Referenced by _sx_sasl_client_process(), _sx_sasl_process(), _sx_sasl_server_process(), and sx_nad_write_elem().
void sx_nad_write_elem (sx_t s, nad_t nad, int elem)
app version
sending a nad
Definition at line 420 of file io.c.
References _sx_event, _sx_nad_write(), event_WANT_READ, event_WANT_WRITE, _sx_st::want_read, and _sx_st::want_write.
Referenced by _router_comp_write(), c2s_router_sx_callback(), and out_packet().
int _sx_raw_write (sx_t s, char * buf, int len)
send raw data out
Definition at line 435 of file io.c.
References _sx_buffer_new(), _sx_debug, jqueue_push(), log_debug, _sx_st::state, state_CLOSING, _sx_st::want_write, _sx_st::wbufq, and ZONE.
Referenced by sx_raw_write().
JABBERD2_API void sx_raw_write (sx_t s, char * buf, int len)
app version
sending raw data
sending raw data (internal)
Definition at line 454 of file io.c.
References _sx_event, _sx_raw_write(), event_WANT_READ, event_WANT_WRITE, _sx_st::want_read, and _sx_st::want_write.
Referenced by _c2s_time_checks(), _router_time_checks(), and _s2s_time_checks().
void _sx_close (sx_t s)
close a stream
Definition at line 470 of file io.c.
References _sx_buffer_new(), _sx_state, jqueue_push(), _sx_st::state, state_CLOSING, state_STREAM_SENT, _sx_st::want_write, and _sx_st::wbufq.
Referenced by _sx_process_read(), _sx_ssl_rio(), _sx_ssl_wio(), and sx_close().
void sx_close (sx_t s)
Definition at line 480 of file io.c.
References _sx_close(), _sx_event, _sx_state, event_CLOSED, event_WANT_WRITE, _sx_st::state, state_CLOSED, state_CLOSING, and state_STREAM_SENT.
Referenced by _c2s_client_sx_callback(), _c2s_component_presence(), _c2s_time_checks(), _out_result(), _out_verify(), _router_process_handshake(), _router_sx_callback(), _s2s_check_conn_routes(), _s2s_time_checks(), _sx_compress_rio(), _sx_compress_wio(), _sx_ssl_handshake(), _sx_ssl_rio(), _sx_ssl_wio(), c2s_router_sx_callback(), JABBER_MAIN(), s2s_router_sx_callback(), and sm_sx_callback().
void sx_kill (sx_t s)
Definition at line 495 of file io.c.
References _sx_event, _sx_state, event_CLOSED, and state_CLOSED.
Referenced by _c2s_client_mio_callback(), _c2s_client_sx_callback(), _in_sx_callback(), _out_mio_callback(), _out_sx_callback(), _router_sx_callback(), c2s_router_mio_callback(), c2s_router_sx_callback(), in_mio_callback(), router_mio_callback(), s2s_router_mio_callback(), s2s_router_sx_callback(), sm_mio_callback(), sm_sx_callback(), and sx_can_write().