jabberd2: sm/sm.h File Reference
sm.h File Reference
data structures and prototypes for the session manager
#include "sx/sx.h"
#include "mio/mio.h"
#include "util/util.h"
#include "storage/storage.h"
#include "util/uri.h"
Data Structures
struct pkt_st
packet summary data wrapper
struct item_st
roster items
struct sm_st
session manager global context
struct user_st
data for a single user
struct sess_st
There is one instance of this struct per user who is logged in to this c2s instance.
struct mm_st
module manager data
struct module_st
data for a single module
struct mod_instance_st
single instance of a module in a chain
Macros
#define DLLEXPORT
#define SM_API
#define ns_AUTH (1)
#define ns_REGISTER (2)
#define ns_ROSTER (3)
#define ns_AGENTS (4)
#define ns_DELAY (5)
#define ns_BROWSE (6)
#define ns_EVENT (7)
#define ns_GATEWAY (8)
#define ns_EXPIRE (9)
#define ns_SEARCH (10)
#define ns_DISCO (11)
#define ns_DISCO_ITEMS (12)
#define ns_DISCO_INFO (13)
#define ns_AMP (14)
#define ns_AMP_ERRORS (15)
#define ns_AMP_ACTION_DROP (16)
#define ns_AMP_ACTION_ERROR (17)
#define ns_AMP_ACTION_NOTIFY (18)
#define ns_AMP_CONDITION_DELIVER (19)
#define ns_AMP_CONDITION_EXPIREAT (20)
#define ns_AMP_CONDITION_MATCHRESOURCE (21)
Typedefs
typedef struct sm_st * sm_t
typedef struct user_st * user_t
typedef struct sess_st * sess_t
typedef struct aci_st * aci_t
typedef struct mm_st * mm_t
typedef struct pkt_st * pkt_t
packet summary data wrapper
typedef struct item_st * item_t
roster items
typedef struct module_st * module_t
typedef struct mod_instance_st * mod_instance_t
Enumerations
enum pkt_type_t {
pkt_NONE = 0x00, pkt_MESSAGE = 0x10, pkt_MESSAGE_CHAT = 0x11, pkt_MESSAGE_HEADLINE = 0x12,
pkt_MESSAGE_GROUPCHAT = 0x14, pkt_PRESENCE = 0x20, pkt_PRESENCE_UN = 0x21, pkt_PRESENCE_PROBE = 0x24,
pkt_S10N = 0x40, pkt_S10N_ED = 0x41, pkt_S10N_UN = 0x42, pkt_S10N_UNED = 0x44,
pkt_IQ = 0x80, pkt_IQ_SET = 0x81, pkt_IQ_RESULT = 0x82, pkt_SESS = 0x100,
pkt_SESS_END = 0x101, pkt_SESS_CREATE = 0x102, pkt_SESS_DELETE = 0x104, pkt_SESS_FAILED = 0x08,
pkt_SESS_MASK = 0x10f, pkt_ERROR = 0x200
}
packet types
enum route_type_t {
route_SINGLE = 0x00, route_MULTI_TO = 0x10, route_MULTI_FROM = 0x11, route_NONE = 0x00,
route_UNICAST = 0x10, route_BROADCAST = 0x11, route_ADV = 0x20, route_ADV_UN = 0x21,
route_ERROR = 0x40
}
route types
enum mod_ret_t { mod_HANDLED, mod_PASS }
module return values
enum mod_chain_t {
chain_SESS_START, chain_SESS_END, chain_IN_SESS, chain_IN_ROUTER,
chain_OUT_SESS, chain_OUT_ROUTER, chain_PKT_SM, chain_PKT_USER,
chain_PKT_ROUTER, chain_USER_LOAD, chain_USER_CREATE, chain_USER_DELETE,
chain_USER_UNLOAD, chain_DISCO_EXTEND
}
module chain types
Functions
SM_API xht aci_load (sm_t sm)
SM_API int aci_check (xht acls, char *type, jid_t jid)
see if a jid is in an acl
SM_API void aci_unload (xht acls)
unload aci table
SM_API int sm_sx_callback (sx_t s, sx_event_t e, void *data, void *arg)
our master callback
SM_API int sm_mio_callback (mio_t m, mio_action_t a, mio_fd_t fd, void *data, void *arg)
SM_API void sm_timestamp (time_t t, char timestamp[18])
SM_API void sm_c2s_action (sess_t dest, char *action, char *target)
send a new action route
SM_API void sm_signature (sm_t sm, char *str)
this is gratuitous, but apache gets one, so why not?
SM_API int sm_register_ns (sm_t sm, char *uri)
register a new global ns
SM_API void sm_unregister_ns (sm_t sm, char *uri)
unregister a global ns
SM_API int sm_get_ns (sm_t sm, char *uri)
get a globally registered ns
SM_API int sm_storage_rate_limit (sm_t sm, const char *owner)
SM_API void dispatch (sm_t sm, pkt_t pkt)
main packet dispatcher
SM_API pkt_t pkt_error (pkt_t pkt, int err)
SM_API pkt_t pkt_tofrom (pkt_t pkt)
swap a packet's to and from attributes
SM_API pkt_t pkt_dup (pkt_t pkt, const char *to, const char *from)
duplicate pkt, replacing addresses
SM_API pkt_t pkt_new (sm_t sm, nad_t nad)
SM_API void pkt_free (pkt_t pkt)
SM_API pkt_t pkt_create (sm_t sm, const char *elem, const char *type, const char *to, const char *from)
SM_API void pkt_id (pkt_t src, pkt_t dest)
convenience - copy the packet id from src to dest
SM_API void pkt_id_new (pkt_t pkt)
create an id value for new iq packets
SM_API void pkt_delay (pkt_t pkt, time_t t, const char *from)
add an x:delay stamp
SM_API void pkt_router (pkt_t pkt)
SM_API void pkt_sess (pkt_t pkt, sess_t sess)
SM_API int pres_trust (user_t user, jid_t jid)
see if the jid is trusted (ie in the roster with s10n="from" or "both")
SM_API void pres_roster (sess_t sess, item_t item)
send presence based on roster changes
SM_API void pres_update (sess_t sess, pkt_t pres)
presence updates from a session
SM_API void pres_error (sess_t sess, jid_t jid)
SM_API void pres_deliver (sess_t sess, pkt_t pres)
outgoing directed presence
SM_API void pres_in (user_t user, pkt_t pres)
presence updates from a remote jid - RFC 3921bis 4.3.2.
SM_API void pres_probe (user_t user)
SM_API void sess_route (sess_t sess, pkt_t pkt)
send a packet to the client for this session
SM_API sess_t sess_start (sm_t sm, jid_t jid)
SM_API void sess_end (sess_t sess)
SM_API sess_t sess_match (user_t user, char *resource)
match a session by resource
SM_API user_t user_load (sm_t sm, jid_t jid)
fetch user data
SM_API void user_free (user_t user)
SM_API int user_create (sm_t sm, jid_t jid)
initialise a user
SM_API void user_delete (sm_t sm, jid_t jid)
trash a user
SM_API void feature_register (sm_t sm, char *feature)
register a feature
SM_API void feature_unregister (sm_t sm, char *feature)
unregister feature
SM_API mm_t mm_new (sm_t sm)
allocate a module manager instance, and loads the modules
SM_API void mm_free (mm_t mm)
free a mm instance
SM_API int mm_sess_start (mm_t mm, sess_t sess)
fire sess-start chain
SM_API void mm_sess_end (mm_t mm, sess_t sess)
fire sess-end chain
SM_API mod_ret_t mm_in_sess (mm_t mm, sess_t sess, pkt_t pkt)
fire in-sess chain
SM_API mod_ret_t mm_in_router (mm_t mm, pkt_t pkt)
fire in-router chain
SM_API mod_ret_t mm_out_sess (mm_t mm, sess_t sess, pkt_t pkt)
fire out-sess chain
SM_API mod_ret_t mm_out_router (mm_t mm, pkt_t pkt)
fire out-router chain
SM_API mod_ret_t mm_pkt_sm (mm_t mm, pkt_t pkt)
fire pkt-sm chain
SM_API mod_ret_t mm_pkt_user (mm_t mm, user_t user, pkt_t pkt)
fire pkt-user chain
SM_API mod_ret_t mm_pkt_router (mm_t mm, pkt_t pkt)
fire pkt-router chain
SM_API int mm_user_load (mm_t mm, user_t user)
fire user-load chain
SM_API int mm_user_unload (mm_t mm, user_t user)
fire user-unload chain
SM_API int mm_user_create (mm_t mm, jid_t jid)
fire user-create chain
SM_API void mm_user_delete (mm_t mm, jid_t jid)
fire user-delete chain
SM_API void mm_disco_extend (mm_t mm, pkt_t pkt)
fire disco-extend chain
Variables
sig_atomic_t sm_lost_router
Detailed Description
data structures and prototypes for the session manager
Author:
Jeremie Miller
Robert Norris
Date:
2005/09/09 05:34:13
Revision:
1.62
Definition in file sm.h.
Macro Definition Documentation
#define DLLEXPORT
Definition at line 54 of file sm.h.
#define SM_API
Definition at line 55 of file sm.h.
#define ns_AUTH (1)
Definition at line 69 of file sm.h.
Referenced by JABBER_MAIN().
#define ns_REGISTER (2)
Definition at line 70 of file sm.h.
Referenced by JABBER_MAIN().
#define ns_ROSTER (3)
Definition at line 71 of file sm.h.
Referenced by _roster_in_sess(), and JABBER_MAIN().
#define ns_AGENTS (4)
Definition at line 72 of file sm.h.
Referenced by _disco_in_sess(), _disco_pkt_sm(), and JABBER_MAIN().
#define ns_DELAY (5)
Definition at line 73 of file sm.h.
Referenced by JABBER_MAIN().
#define ns_BROWSE (6)
Definition at line 74 of file sm.h.
Referenced by JABBER_MAIN().
#define ns_EVENT (7)
Definition at line 75 of file sm.h.
Referenced by JABBER_MAIN().
#define ns_GATEWAY (8)
Definition at line 76 of file sm.h.
Referenced by JABBER_MAIN().
#define ns_EXPIRE (9)
Definition at line 77 of file sm.h.
Referenced by JABBER_MAIN().
#define ns_SEARCH (10)
Definition at line 78 of file sm.h.
Referenced by JABBER_MAIN().
#define ns_DISCO (11)
Definition at line 79 of file sm.h.
Referenced by JABBER_MAIN().
#define ns_DISCO_ITEMS (12)
Definition at line 80 of file sm.h.
Referenced by _disco_pkt_sm(), and JABBER_MAIN().
#define ns_DISCO_INFO (13)
Definition at line 81 of file sm.h.
Referenced by _amp_pkt_sm(), _disco_in_sess(), _disco_pkt_sm(), _pep_out_sess(), and JABBER_MAIN().
#define ns_AMP (14)
Definition at line 83 of file sm.h.
#define ns_AMP_ERRORS (15)
Definition at line 84 of file sm.h.
#define ns_AMP_ACTION_DROP (16)
Definition at line 85 of file sm.h.
#define ns_AMP_ACTION_ERROR (17)
Definition at line 86 of file sm.h.
#define ns_AMP_ACTION_NOTIFY (18)
Definition at line 87 of file sm.h.
#define ns_AMP_CONDITION_DELIVER (19)
Definition at line 88 of file sm.h.
#define ns_AMP_CONDITION_EXPIREAT (20)
Definition at line 89 of file sm.h.
#define ns_AMP_CONDITION_MATCHRESOURCE (21)
Definition at line 90 of file sm.h.
Typedef Documentation
typedef struct sm_st* sm_t
Definition at line 59 of file sm.h.
typedef struct user_st* user_t
Definition at line 60 of file sm.h.
typedef struct sess_st* sess_t
Definition at line 61 of file sm.h.
typedef struct aci_st* aci_t
Definition at line 62 of file sm.h.
typedef struct mm_st* mm_t
Definition at line 63 of file sm.h.
typedef struct pkt_st * pkt_t
packet summary data wrapper
typedef struct item_st * item_t
roster items
typedef struct module_st* module_t
Definition at line 358 of file sm.h.
typedef struct mod_instance_st* mod_instance_t
Definition at line 359 of file sm.h.
Enumeration Type Documentation
enum pkt_type_t
packet types
Enumerator:
pkt_NONE
no packet
pkt_MESSAGE
message
pkt_MESSAGE_CHAT
message (chat)
pkt_MESSAGE_HEADLINE
message (headline)
pkt_MESSAGE_GROUPCHAT
message (groupchat)
pkt_PRESENCE
presence
pkt_PRESENCE_UN
presence (unavailable)
pkt_PRESENCE_PROBE
presence (probe)
pkt_S10N
subscribe request
pkt_S10N_ED
subscribed response
pkt_S10N_UN
unsubscribe request
pkt_S10N_UNED
unsubscribed response
pkt_IQ
info/query (get)
pkt_IQ_SET
info/query (set)
pkt_IQ_RESULT
info/query (result)
pkt_SESS
session start request
pkt_SESS_END
session end request
pkt_SESS_CREATE
session create request
pkt_SESS_DELETE
session delete request
pkt_SESS_FAILED
session request failed (mask)
pkt_SESS_MASK
session request (mask)
pkt_ERROR
packet error
Definition at line 93 of file sm.h.
enum route_type_t
route types
Enumerator:
route_SINGLE
single component route
route_MULTI_TO
multi component route - route by 'to'
route_MULTI_FROM
multi component route - route by 'from'
route_NONE
no route
route_UNICAST
unicast
route_BROADCAST
broadcast
route_ADV
advertisement (available)
route_ADV_UN
advertisement (unavailable)
route_ERROR
route error
Definition at line 119 of file sm.h.
enum mod_ret_t
module return values
Enumerator:
mod_HANDLED
packet was handled (and freed)
mod_PASS
packet was unhandled, should be passed to the next module
Definition at line 335 of file sm.h.
enum mod_chain_t
module chain types
Enumerator:
chain_SESS_START
session start, load per-session data
chain_SESS_END
session ended, save & free per-session data
chain_IN_SESS
packet from an active session
chain_IN_ROUTER
packet from the router
chain_OUT_SESS
packet to an active session
chain_OUT_ROUTER
packet to a router
chain_PKT_SM
packet for the sm itself
chain_PKT_USER
packet for a user
chain_PKT_ROUTER
packet from the router (special purpose)
chain_USER_LOAD
user loaded, load per-user data
chain_USER_CREATE
user creation, generate and save per-user data
chain_USER_DELETE
user deletion, delete saved per-user data
chain_USER_UNLOAD
user is about to be unloaded
chain_DISCO_EXTEND
disco request, extend sm disco::info
Definition at line 341 of file sm.h.
Function Documentation
SM_API xht aci_load (sm_t sm)
Definition at line 30 of file aci.c.
References sm_st::config, jid_append(), jid_free(), jid_new(), jid_user(), log_debug, config_st::nad, NAD_AVAL, NAD_AVAL_L, NAD_CDATA, NAD_CDATA_L, nad_find_attr(), nad_find_elem(), pstrdup(), xhash_new(), xhash_pool(), xhash_put(), and ZONE.
SM_API int aci_check (xht acls, char * type, jid_t jid)
see if a jid is in an acl
Definition at line 86 of file aci.c.
References jid_st::dirty, jid_dup(), jid_free(), jid_full(), jid_search(), jid_user(), log_debug, jid_st::resource, xhash_get(), and ZONE.
SM_API void aci_unload (xht acls)
unload aci table
Definition at line 114 of file aci.c.
References jid_free(), log_debug, aci_user_st::name, aci_user_st::next, jid_st::next, xhash_free(), xhash_iter_first(), xhash_iter_get(), xhash_iter_next(), and ZONE.
Referenced by JABBER_MAIN().
SM_API int sm_sx_callback (sx_t s, sx_event_t e, void * data, void * arg)
our master callback
Definition at line 33 of file sm.c.
References _sx_error_st::code, _sx_buf_st::data, dispatch(), event_CLOSED, event_ERROR, event_OPEN, event_PACKET, event_READ, event_STREAM, event_WANT_READ, event_WANT_WRITE, event_WRITE, mio_fd_st::fd, sm_st::fd, _sx_error_st::generic, sm_st::hosts, sm_st::id, _sx_buf_st::len, sm_st::log, log_debug, log_write(), sm_st::mio, mio_close, MIO_ERROR, mio_read, MIO_STRERROR, MIO_WOULDBLOCK, mio_write, nad_add_namespace(), nad_append_attr(), nad_append_elem(), NAD_AVAL, NAD_AVAL_L, NAD_ENAME, NAD_ENAME_L, NAD_ENS, nad_find_attr(), nad_find_elem(), nad_find_scoped_namespace(), nad_free(), nad_new(), NAD_NURI, NAD_NURI_L, nad_set_attr(), sm_st::online, pkt_new(), sm_st::retry_left, sm_st::retry_lost, sm_st::router, sm_st::router_pass, sm_st::router_user, sm, _sx_error_st::specific, _sx_st::ssf, sm_st::started, _sx_st::state, state_OPEN, state_STREAM, sx_close(), SX_ERR_AUTH, sx_kill(), sx_nad_write, sm_st::sx_sasl, sx_sasl_auth(), sm_st::sx_ssl, sx_ssl_client_starttls(), uri_COMPONENT, uri_STREAMS, uri_TLS, xhash_iter_first(), xhash_iter_get(), xhash_iter_next(), and ZONE.
Referenced by _sm_router_connect().
SM_API int sm_mio_callback (mio_t m, mio_action_t a, mio_fd_t fd, void * data, void * arg)
Definition at line 241 of file sm.c.
References action_ACCEPT, action_CLOSE, action_READ, action_WRITE, mio_fd_st::fd, sm_st::log, log_debug, log_write(), sm_st::online, sm_st::router, sm, sm_lost_router, sx_can_read(), sx_can_write(), sx_kill(), and ZONE.
Referenced by _sm_router_connect().
SM_API void sm_timestamp (time_t t, char timestamp[18])
SM_API void sm_c2s_action (sess_t dest, char * action, char * target)
send a new action route
Definition at line 280 of file sm.c.
References sess_st::c2s, sess_st::c2s_id, sm_st::id, log_debug, nad_add_namespace(), nad_append_attr(), nad_append_elem(), nad_new(), sm_st::router, user_st::sm, sess_st::sm_id, sx_nad_write, uri_COMPONENT, uri_SESSION, sess_st::user, and ZONE.
Referenced by _session_in_router(), JABBER_MAIN(), sess_start(), sm_storage_rate_limit(), and user_delete().
SM_API void sm_signature (sm_t sm, char * str)
this is gratuitous, but apache gets one, so why not?
Definition at line 313 of file sm.c.
References sm_st::siglen, and sm_st::signature.
Referenced by JABBER_MAIN().
SM_API int sm_register_ns (sm_t sm, char * uri)
register a new global ns
Definition at line 324 of file sm.c.
References pstrdup(), xhash_count(), xhash_get(), xhash_pool(), xhash_put(), sm_st::xmlns, and sm_st::xmlns_refcount.
Referenced by module_init().
SM_API void sm_unregister_ns (sm_t sm, char * uri)
unregister a global ns
Definition at line 338 of file sm.c.
References xhash_get(), xhash_put(), xhash_zap(), sm_st::xmlns, and sm_st::xmlns_refcount.
Referenced by _iq_last_free(), _iq_ping_free(), _iq_private_free(), _iq_time_free(), _iq_vcard_free(), _iq_version_free(), _privacy_free(), and _vacation_free().
SM_API int sm_get_ns (sm_t sm, char * uri)
get a globally registered ns
Definition at line 349 of file sm.c.
References xhash_get(), and sm_st::xmlns.
SM_API int sm_storage_rate_limit (sm_t sm, const char * owner)
Definition at line 355 of file sm.c.
References item_st::jid, user_st::jid, jid_full(), sm_st::log, log_debug, log_write(), sess_st::next, pkt_create(), pkt_router(), pool_cleanup(), pstrdup(), sm_st::query_rate_seconds, sm_st::query_rate_total, sm_st::query_rate_wait, sm_st::query_rates, rate_add(), rate_check(), rate_free(), rate_new(), user_st::roster, user_st::sessions, user_st::sm, sm_c2s_action(), item_st::to, sm_st::users, xhash_get(), xhash_iter_first(), xhash_iter_get(), xhash_iter_next(), xhash_pool(), xhash_put(), and ZONE.
Referenced by _iq_vcard_in_sess(), _iq_vcard_pkt_user(), _roster_in_sess_s10n(), _roster_pkt_user(), and _roster_set_item().
SM_API void dispatch (sm_t sm, pkt_t pkt)
main packet dispatcher
Definition at line 31 of file dispatch.c.
References _stanza_errors, _stanza_error_st::code, pkt_st::from, jid_full(), log_debug, sm_st::mm, mm_in_router(), mm_pkt_router(), mm_pkt_sm(), mm_pkt_user(), mod_HANDLED, mod_PASS, pkt_st::nad, NAD_AVAL, NAD_AVAL_L, nad_find_attr(), jid_st::node, pkt_create(), pkt_error(), pkt_free(), pkt_IQ_RESULT, pkt_PRESENCE, pkt_PRESENCE_PROBE, pkt_router(), route_BROADCAST, route_ERROR, route_UNICAST, pkt_st::rtype, user_st::sessions, pkt_st::sm, stanza_err_BAD_REQUEST, stanza_err_FEATURE_NOT_IMPLEMENTED, stanza_err_REMOTE_SERVER_NOT_FOUND, stanza_err_SERVICE_UNAVAILABLE, pkt_st::to, pkt_st::type, user_free(), user_load(), and ZONE.
Referenced by sm_sx_callback().
SM_API pkt_t pkt_error (pkt_t pkt, int err)
Definition at line 30 of file pkt.c.
References jid_dup(), log_debug, pkt_st::nad, pkt_ERROR, pkt_free(), pkt_tofrom(), pkt_st::rto, stanza_error(), pkt_st::to, pkt_st::type, and ZONE.
Referenced by _offline_user_delete(), _privacy_out_router(), _session_in_router(), dispatch(), pkt_router(), and pkt_sess().
SM_API pkt_t pkt_tofrom (pkt_t pkt)
swap a packet's to and from attributes
Definition at line 57 of file pkt.c.
References pkt_st::from, jid_full(), pkt_st::nad, nad_set_attr(), pkt_st::rfrom, pkt_st::rto, and pkt_st::to.
Referenced by _disco_in_sess_result(), _echo_pkt_sm(), _iq_last_pkt_sm(), _iq_last_pkt_user(), _iq_ping_pkt_sm(), _iq_private_in_sess(), _iq_time_pkt_sm(), _iq_version_pkt_sm(), _roster_in_sess(), _roster_pkt_user(), _vacation_in_sess(), and pkt_error().
SM_API pkt_t pkt_dup (pkt_t pkt, const char * to, const char * from)
duplicate pkt, replacing addresses
Definition at line 84 of file pkt.c.
References pkt_st::from, jid_dup(), jid_full(), jid_new(), log_debug, pkt_st::nad, nad_copy(), nad_set_attr(), pkt_st::sm, pkt_st::to, pkt_st::type, and ZONE.
Referenced by _announce_pkt_sm(), _disco_in_sess(), _disco_pkt_sm(), _help_pkt_sm(), _iq_private_in_sess(), _offline_pkt_user(), _privacy_in_sess(), _roster_push(), _unblock_jid(), pres_in(), pres_roster(), and pres_update().
SM_API pkt_t pkt_new (sm_t sm, nad_t nad)
Definition at line 113 of file pkt.c.
References nad_st::ecur, pkt_st::from, jid_new(), sm_st::log, log_debug, log_write(), pkt_st::nad, NAD_AVAL, NAD_AVAL_L, NAD_CDATA, NAD_CDATA_L, NAD_ENAME, NAD_ENAME_L, NAD_ENS, nad_find_attr(), nad_find_elem(), nad_find_namespace(), nad_free(), NAD_NURI, NAD_NURI_L, pkt_st::ns, pkt_ERROR, pkt_free(), pkt_IQ, pkt_IQ_RESULT, pkt_IQ_SET, pkt_MESSAGE, pkt_MESSAGE_CHAT, pkt_MESSAGE_GROUPCHAT, pkt_MESSAGE_HEADLINE, pkt_PRESENCE, pkt_PRESENCE_PROBE, pkt_PRESENCE_UN, pkt_S10N, pkt_S10N_ED, pkt_S10N_UN, pkt_S10N_UNED, pkt_SESS, pkt_SESS_CREATE, pkt_SESS_DELETE, pkt_SESS_END, pkt_SESS_FAILED, pkt_st::pri, pkt_st::rfrom, route_ADV, route_ADV_UN, route_BROADCAST, route_ERROR, route_UNICAST, pkt_st::rto, pkt_st::rtype, sm, pkt_st::sm, pkt_st::to, pkt_st::type, uri_CLIENT, uri_COMPONENT, uri_SESSION, xhash_getx(), sm_st::xmlns, and ZONE.
Referenced by _announce_broadcast_user(), _announce_in_sess(), _iq_private_in_sess(), _offline_in_sess(), _offline_user_delete(), pkt_create(), pres_in(), and sm_sx_callback().
SM_API void pkt_free (pkt_t pkt)
Definition at line 315 of file pkt.c.
References pkt_st::from, jid_free(), log_debug, pkt_st::nad, nad_free(), pkt_st::rfrom, pkt_st::rto, pkt_st::to, and ZONE.
Referenced by _amp_pkt_sm(), _amp_pkt_user(), _announce_pkt_sm(), _deliver_in_sess(), _deliver_pkt_user(), _disco_free(), _disco_generate_packets(), _disco_in_sess(), _disco_pkt_router(), _disco_pkt_sm(), _disco_pkt_sm_populate(), _help_pkt_sm(), _iq_private_in_sess(), _iq_vcard_in_sess(), _iq_vcard_pkt_sm(), _iq_vcard_pkt_user(), _offline_in_sess(), _offline_pkt_user(), _offline_user_delete(), _presence_in_router(), _presence_pkt_sm(), _presence_pkt_user(), _privacy_in_router(), _privacy_in_sess(), _privacy_out_router(), _roster_in_sess(), _roster_in_sess_s10n(), _roster_pkt_user(), _roster_set_item(), _session_in_router(), _vacation_in_sess(), _vacation_pkt_user(), dispatch(), pkt_error(), pkt_new(), pkt_router(), pkt_sess(), pres_deliver(), pres_in(), and pres_update().
SM_API pkt_t pkt_create (sm_t sm, const char * elem, const char * type, const char * to, const char * from)
Definition at line 328 of file pkt.c.
References nad_add_namespace(), nad_append_attr(), nad_append_elem(), nad_new(), pkt_new(), uri_CLIENT, uri_COMPONENT, and uri_SESSION.
Referenced by _amp_pkt_sm(), _announce_pkt_sm(), _disco_agents_result(), _disco_info_result(), _disco_items_result(), _disco_pkt_router(), _disco_pkt_sm(), _echo_pkt_sm(), _help_pkt_sm(), _iq_private_in_sess(), _iq_vcard_in_sess(), _iq_vcard_to_pkt(), _offline_pkt_user(), _presence_pkt_sm(), _privacy_in_sess(), _roster_in_sess(), _roster_in_sess_s10n(), _roster_pkt_user(), _roster_set_item(), _roster_update_walker(), _sess_end_guts(), _status_pkt_sm(), _vacation_in_sess(), _vacation_pkt_user(), amp_build_response_pkt(), dispatch(), pres_in(), pres_probe(), pres_roster(), pres_update(), and sm_storage_rate_limit().
SM_API void pkt_id (pkt_t src, pkt_t dest)
convenience - copy the packet id from src to dest
Definition at line 353 of file pkt.c.
References pkt_st::nad, NAD_AVAL, NAD_AVAL_L, nad_find_attr(), and nad_set_attr().
Referenced by _amp_pkt_sm(), _disco_in_sess(), _disco_pkt_sm(), _iq_private_in_sess(), _iq_vcard_in_sess(), _iq_vcard_pkt_sm(), _iq_vcard_pkt_user(), _privacy_in_sess(), _roster_in_sess(), _vacation_in_sess(), and amp_build_response_pkt().
SM_API void pkt_id_new (pkt_t pkt)
create an id value for new iq packets
Definition at line 364 of file pkt.c.
References pkt_st::nad, and nad_set_attr().
Referenced by _disco_pkt_router(), _iq_private_in_sess(), _privacy_in_sess(), _roster_in_sess_s10n(), _roster_pkt_user(), _roster_set_item(), and _roster_update_walker().
SM_API void pkt_delay (pkt_t pkt, time_t t, const char * from)
add an x:delay stamp
Definition at line 508 of file pkt.c.
References datetime_out(), dt_DATETIME, dt_LEGACY, log_debug, pkt_st::nad, nad_add_namespace(), nad_insert_elem(), nad_set_attr(), uri_DELAY, uri_URN_DELAY, and ZONE.
Referenced by _announce_pkt_sm(), _offline_pkt_user(), and pres_update().
SM_API void pkt_router (pkt_t pkt)
Definition at line 379 of file pkt.c.
References jid_st::domain, nad_st::elems, sm_st::id, jid_free(), jid_new(), log_debug, sm_st::mm, mm_out_router(), mod_HANDLED, mod_PASS, pkt_st::nad, nad_find_elem(), nad_find_namespace(), nad_set_attr(), nad_ns_st::next, nad_elem_st::ns, nad_st::nss, pkt_error(), pkt_free(), pkt_router(), pkt_st::rfrom, sm_st::router, pkt_st::rto, pkt_st::sm, sx_nad_write, pkt_st::to, uri_SESSION, and ZONE.
Referenced by _amp_pkt_sm(), _amp_pkt_user(), _announce_broadcast_user(), _announce_in_sess(), _announce_pkt_sm(), _deliver_in_sess(), _disco_pkt_router(), _disco_pkt_sm(), _echo_pkt_sm(), _help_pkt_sm(), _iq_last_pkt_sm(), _iq_last_pkt_user(), _iq_ping_pkt_sm(), _iq_time_pkt_sm(), _iq_vcard_pkt_sm(), _iq_vcard_pkt_user(), _iq_version_pkt_sm(), _offline_pkt_user(), _offline_user_delete(), _presence_pkt_sm(), _privacy_in_sess(), _roster_pkt_user(), _roster_set_item(), _status_pkt_sm(), _unblock_jid(), _vacation_pkt_user(), dispatch(), pkt_router(), pkt_sess(), pres_deliver(), pres_in(), pres_probe(), pres_roster(), pres_update(), and sm_storage_rate_limit().
SM_API void pkt_sess (pkt_t pkt, sess_t sess)
Definition at line 459 of file pkt.c.
References sess_st::c2s, jid_st::domain, sm_st::id, sess_st::jid, jid_free(), jid_full(), jid_new(), log_debug, sm_st::mm, mm_out_sess(), mod_HANDLED, mod_PASS, pkt_st::nad, nad_set_attr(), pkt_error(), pkt_free(), pkt_router(), pkt_st::rfrom, pkt_st::rto, sess_route(), pkt_st::sm, and ZONE.
Referenced by _deliver_pkt_user(), _disco_in_sess(), _disco_in_sess_result(), _iq_ping_in_sess(), _iq_private_in_sess(), _iq_vcard_in_sess(), _offline_in_sess(), _offline_pkt_user(), _presence_pkt_user(), _privacy_in_sess(), _privacy_out_router(), _roster_in_sess(), _roster_push(), _roster_update_walker(), _session_in_router(), _vacation_in_sess(), and pres_in().
SM_API int pres_trust (user_t user, jid_t jid)
see if the jid is trusted (ie in the roster with s10n="from" or "both")
Definition at line 337 of file pres.c.
References item_st::from, user_st::jid, jid_compare_user(), jid_full(), jid_user(), user_st::roster, and xhash_get().
Referenced by _iq_last_pkt_user(), _privacy_in_sess(), _unblock_jid(), pres_deliver(), pres_in(), and pres_update().
SM_API void pres_roster (sess_t sess, item_t item)
send presence based on roster changes
Definition at line 359 of file pres.c.
References sess_st::A, sess_st::available, sess_st::E, item_st::from, item_st::jid, sess_st::jid, jid_full(), jid_search(), log_debug, pkt_create(), pkt_dup(), pkt_router(), sess_st::pres, user_st::sm, sess_st::user, and ZONE.
Referenced by _roster_in_sess_s10n(), _roster_pkt_user(), and _roster_set_item().
SM_API void pres_update (sess_t sess, pkt_t pres)
presence updates from a session
Definition at line 72 of file pres.c.
References _pres_top(), sess_st::A, sess_st::available, sess_st::E, sess_st::fake, pkt_st::from, item_st::from, item_st::jid, sess_st::jid, jid_free(), jid_full(), jid_search(), jid_user(), log_debug, jid_st::next, sess_st::next, pkt_create(), pkt_delay(), pkt_dup(), pkt_free(), pkt_PRESENCE, pkt_PRESENCE_UN, pkt_router(), sess_st::pres, pres_trust(), pkt_st::pri, sess_st::pri, user_st::roster, user_st::sessions, user_st::sm, item_st::to, pkt_st::type, sess_st::user, xhash_iter_first(), xhash_iter_get(), xhash_iter_next(), and ZONE.
Referenced by _presence_in_sess().
SM_API void pres_error (sess_t sess, jid_t jid)
Definition at line 296 of file pres.c.
References sess_st::A, sess_st::E, jid_append(), jid_full(), jid_zap(), log_debug, and ZONE.
Referenced by _presence_pkt_user().
SM_API void pres_deliver (sess_t sess, pkt_t pres)
outgoing directed presence
Definition at line 304 of file pres.c.
References sess_st::A, sess_st::E, jid_append(), jid_full(), jid_zap(), log_debug, pkt_free(), pkt_PRESENCE, pkt_PRESENCE_UN, pkt_router(), pres_trust(), pkt_st::to, pkt_st::type, sess_st::user, and ZONE.
Referenced by _presence_in_sess().
SM_API void pres_in (user_t user, pkt_t pkt)
presence updates from a remote jid - RFC 3921bis 4.3.2.
Definition at line 212 of file pres.c.
References user_st::available, sess_st::available, sess_st::E, sess_st::fake, pkt_st::from, user_st::jid, sess_st::jid, jid_compare_full(), jid_full(), jid_user(), jid_zap(), log_debug, pkt_st::nad, nad_copy(), nad_set_attr(), sess_st::next, pkt_create(), pkt_dup(), pkt_free(), pkt_new(), pkt_PRESENCE_PROBE, pkt_router(), pkt_sess(), sess_st::pres, pres_trust(), jid_st::resource, user_st::sessions, pkt_st::sm, user_st::sm, sm_st::st, pkt_st::to, pkt_st::type, and ZONE.
Referenced by _presence_pkt_user().
SM_API void pres_probe (user_t user)
Definition at line 380 of file pres.c.
References item_st::jid, user_st::jid, jid_full(), jid_user(), log_debug, pkt_create(), pkt_router(), user_st::roster, user_st::sm, item_st::to, xhash_iter_first(), xhash_iter_get(), xhash_iter_next(), and ZONE.
SM_API void sess_route (sess_t sess, pkt_t pkt)
send a packet to the client for this session
Definition at line 31 of file sess.c.
References sess_st::c2s, sess_st::c2s_id, jid_st::domain, pkt_st::from, user_st::jid, sess_st::jid, jid_free(), jid_full(), log_debug, pkt_st::nad, nad_append_namespace(), nad_set_attr(), pkt_st::rfrom, sm_st::router, pkt_st::rto, user_st::sm, sess_st::sm_id, sx_nad_write, pkt_st::to, uri_SESSION, sess_st::user, and ZONE.
Referenced by pkt_sess().
SM_API sess_t sess_start (sm_t sm, jid_t jid)
Definition at line 103 of file sess.c.
References _sess_end_guts(), sess_st::c2s_id, sm_st::config, config_get(), datetime_out(), jid_st::domain, dt_DATETIME, hex_from_raw(), sm_st::hosts, sess_st::jid, jid_compare_full(), jid_dup(), jid_free(), jid_full(), jid_user(), sm_st::log, log_debug, log_write(), sm_st::mm, mm_sess_start(), sess_st::module_data, sess_st::next, mm_st::nindex, sess_st::p, pmalloco(), pool_cleanup(), pool_free(), pool_new, sess_st::pri, sm_st::sessions, user_st::sessions, sha1_append(), sha1_finish(), sha1_init(), user_st::sm, sm_c2s_action(), sess_st::sm_id, sess_st::user, user_create(), user_load(), xhash_get(), xhash_put(), and ZONE.
Referenced by _session_in_router().
SM_API void sess_end (sess_t sess)
Definition at line 85 of file sess.c.
References _sess_end_guts(), sess_st::jid, jid_full(), jid_user(), sm_st::log, log_debug, log_write(), sm_st::mm, mm_user_unload(), sess_st::p, pool_free(), user_st::sessions, user_st::sm, sess_st::user, user_free(), and ZONE.
Referenced by _session_in_router(), _session_pkt_router(), JABBER_MAIN(), and user_delete().
SM_API sess_t sess_match (user_t user, char * resource)
match a session by resource
Definition at line 206 of file sess.c.
References sess_st::jid, sess_st::next, jid_st::resource, and user_st::sessions.
Referenced by _amp_pkt_user(), _deliver_pkt_user(), _presence_pkt_user(), _privacy_in_router(), and _privacy_out_router().
SM_API user_t user_load (sm_t sm, jid_t jid)
fetch user data
Definition at line 52 of file user.c.
References _user_alloc(), user_st::jid, jid_user(), log_debug, sm_st::mm, mm_user_load(), user_st::p, pool_free(), sm_st::users, xhash_get(), xhash_put(), and ZONE.
Referenced by _privacy_in_router(), _privacy_out_router(), dispatch(), sess_start(), user_create(), and user_delete().
SM_API void user_free (user_t user)
Definition at line 80 of file user.c.
References user_st::jid, jid_user(), log_debug, user_st::p, pool_free(), user_st::sm, sm_st::users, xhash_zap(), and ZONE.
Referenced by dispatch(), and sess_end().
SM_API int user_create (sm_t sm, jid_t jid)
initialise a user
Definition at line 88 of file user.c.
References jid_st::domain, sm_st::hosts, jid_user(), sm_st::log, log_debug, log_write(), sm_st::mm, mm_user_create(), mm_user_delete(), user_load(), xhash_get(), and ZONE.
Referenced by _session_in_router(), and sess_start().
SM_API void user_delete (sm_t sm, jid_t jid)
trash a user
Definition at line 121 of file user.c.
References jid_user(), sm_st::log, log_debug, log_write(), sm_st::mm, mm_user_delete(), sess_st::next, sess_end(), user_st::sessions, sm_c2s_action(), user_load(), and ZONE.
Referenced by _session_in_router().
SM_API void feature_register (sm_t sm, char * feature)
register a feature
Definition at line 37 of file feature.c.
References sm_st::features, log_debug, pstrdup(), xhash_get(), xhash_pool(), xhash_put(), and ZONE.
Referenced by JABBER_MAIN(), and module_init().
SM_API void feature_unregister (sm_t sm, char * feature)
unregister feature
Definition at line 45 of file feature.c.
References sm_st::features, log_debug, xhash_get(), xhash_put(), xhash_zap(), and ZONE.
Referenced by _iq_last_free(), _iq_ping_free(), _iq_private_free(), _iq_time_free(), _iq_vcard_free(), _iq_version_free(), _presence_free(), _privacy_free(), and _vacation_free().
SM_API mm_t mm_new (sm_t sm)
allocate a module manager instance, and loads the modules
Definition at line 47 of file mm.c.
References chain_DISCO_EXTEND, chain_IN_ROUTER, chain_IN_SESS, chain_OUT_ROUTER, chain_OUT_SESS, chain_PKT_ROUTER, chain_PKT_SM, chain_PKT_USER, chain_SESS_END, chain_SESS_START, chain_USER_CREATE, chain_USER_DELETE, chain_USER_LOAD, chain_USER_UNLOAD, sm_st::config, config_get_one(), mm_st::disco_extend, module_st::handle, mm_st::in_router, mm_st::in_sess, module_st::index, module_st::init, sm_st::log, log_debug, log_write(), module_st::mm, module_st::module_init_fn, mm_st::modules, config_st::nad, NAD_AVAL, NAD_AVAL_L, NAD_CDATA, NAD_CDATA_L, nad_find_attr(), nad_find_elem(), module_st::name, mm_st::ndisco_extend, mm_st::nin_router, mm_st::nin_sess, mm_st::nindex, mm_st::nout_router, mm_st::nout_sess, mm_st::npkt_router, mm_st::npkt_sm, mm_st::npkt_user, mm_st::nsess_end, mm_st::nsess_start, mm_st::nuser_create, mm_st::nuser_delete, mm_st::nuser_load, mm_st::nuser_unload, mm_st::out_router, mm_st::out_sess, PATH_MAX, mm_st::pkt_router, mm_st::pkt_sm, mm_st::pkt_user, mm_st::sess_end, mm_st::sess_start, sm, mm_st::sm, mm_st::user_create, mm_st::user_delete, mm_st::user_load, mm_st::user_unload, xhash_get(), xhash_new(), xhash_put(), xhash_zap(), and ZONE.
Referenced by _sm_signal_hup(), and JABBER_MAIN().
SM_API void mm_free (mm_t mm)
free a mm instance
Definition at line 290 of file mm.c.
References _mm_reaper(), mm_st::disco_extend, mm_st::in_router, mm_st::in_sess, mm_st::modules, mm_st::ndisco_extend, mm_st::nin_router, mm_st::nin_sess, mm_st::nout_router, mm_st::nout_sess, mm_st::npkt_router, mm_st::npkt_sm, mm_st::npkt_user, mm_st::nsess_end, mm_st::nsess_start, mm_st::nuser_create, mm_st::nuser_delete, mm_st::nuser_load, mm_st::out_router, mm_st::out_sess, mm_st::pkt_router, mm_st::pkt_sm, mm_st::pkt_user, mm_st::sess_end, mm_st::sess_start, mm_st::user_create, mm_st::user_delete, mm_st::user_load, xhash_free(), and xhash_walk().
Referenced by _sm_signal_hup(), and JABBER_MAIN().
SM_API int mm_sess_start (mm_t mm, sess_t sess)
fire sess-start chain
Definition at line 383 of file mm.c.
References log_debug, mod_instance_st::mod, module_st::name, mm_st::nsess_start, mm_st::sess_start, module_st::sess_start, and ZONE.
Referenced by sess_start().
SM_API void mm_sess_end (mm_t mm, sess_t sess)
fire sess-end chain
Definition at line 414 of file mm.c.
References log_debug, mod_instance_st::mod, module_st::name, mm_st::nsess_end, mm_st::sess_end, module_st::sess_end, and ZONE.
Referenced by _sess_end_guts().
SM_API mod_ret_t mm_in_sess (mm_t mm, sess_t sess, pkt_t pkt)
fire in-sess chain
Definition at line 440 of file mm.c.
References mm_st::in_sess, module_st::in_sess, log_debug, mod_instance_st::mod, mod_PASS, module_st::name, mm_st::nin_sess, and ZONE.
Referenced by _sess_end_guts(), and _session_in_router().
SM_API mod_ret_t mm_in_router (mm_t mm, pkt_t pkt)
fire in-router chain
Definition at line 472 of file mm.c.
References mm_st::in_router, module_st::in_router, log_debug, mod_instance_st::mod, mod_PASS, module_st::name, mm_st::nin_router, and ZONE.
Referenced by dispatch().
SM_API mod_ret_t mm_out_sess (mm_t mm, sess_t sess, pkt_t pkt)
fire out-sess chain
Definition at line 504 of file mm.c.
References log_debug, mod_instance_st::mod, mod_PASS, module_st::name, mm_st::nout_sess, mm_st::out_sess, module_st::out_sess, and ZONE.
Referenced by pkt_sess().
SM_API mod_ret_t mm_out_router (mm_t mm, pkt_t pkt)
fire out-router chain
Definition at line 535 of file mm.c.
References log_debug, mod_instance_st::mod, mod_PASS, module_st::name, mm_st::nout_router, mm_st::out_router, module_st::out_router, and ZONE.
Referenced by pkt_router().
SM_API mod_ret_t mm_pkt_sm (mm_t mm, pkt_t pkt)
fire pkt-sm chain
Definition at line 566 of file mm.c.
References log_debug, mod_instance_st::mod, mod_PASS, module_st::name, mm_st::npkt_sm, mm_st::pkt_sm, module_st::pkt_sm, and ZONE.
Referenced by dispatch().
SM_API mod_ret_t mm_pkt_user (mm_t mm, user_t user, pkt_t pkt)
fire pkt-user chain
Definition at line 596 of file mm.c.
References log_debug, mod_instance_st::mod, mod_PASS, module_st::name, mm_st::npkt_user, mm_st::pkt_user, module_st::pkt_user, and ZONE.
Referenced by dispatch().
SM_API mod_ret_t mm_pkt_router (mm_t mm, pkt_t pkt)
fire pkt-router chain
Definition at line 627 of file mm.c.
References log_debug, mod_instance_st::mod, mod_PASS, module_st::name, mm_st::npkt_router, mm_st::pkt_router, module_st::pkt_router, and ZONE.
Referenced by dispatch().
SM_API int mm_user_load (mm_t mm, user_t user)
fire user-load chain
Definition at line 658 of file mm.c.
References log_debug, mod_instance_st::mod, module_st::name, mm_st::nuser_load, mm_st::user_load, module_st::user_load, and ZONE.
Referenced by user_load().
SM_API int mm_user_unload (mm_t mm, user_t user)
fire user-unload chain
Definition at line 689 of file mm.c.
References log_debug, mod_instance_st::mod, module_st::name, mm_st::nuser_unload, mm_st::user_unload, module_st::user_unload, and ZONE.
Referenced by sess_end().
SM_API int mm_user_create (mm_t mm, jid_t jid)
fire user-create chain
Definition at line 720 of file mm.c.
References log_debug, mod_instance_st::mod, module_st::name, mm_st::nuser_create, mm_st::user_create, module_st::user_create, and ZONE.
Referenced by user_create().
SM_API void mm_user_delete (mm_t mm, jid_t jid)
fire user-delete chain
Definition at line 751 of file mm.c.
References log_debug, mod_instance_st::mod, module_st::name, mm_st::nuser_delete, mm_st::user_delete, module_st::user_delete, and ZONE.
Referenced by user_create(), and user_delete().
SM_API void mm_disco_extend (mm_t mm, pkt_t pkt)
fire disco-extend chain
Definition at line 777 of file mm.c.
References mm_st::disco_extend, module_st::disco_extend, log_debug, mod_instance_st::mod, module_st::name, mm_st::ndisco_extend, and ZONE.
Referenced by _disco_info_result().
Variable Documentation
sig_atomic_t sm_lost_router
Definition at line 30 of file sm.c.
Referenced by _sm_router_connect(), _sm_signal(), JABBER_MAIN(), and sm_mio_callback().