jabberd2: sx/ssl.c File Reference
ssl.c File Reference
#include "sx.h"
#include <openssl/x509_vfy.h>
Functions
static int _sx_ssl_verify_callback (int preverify_ok, X509_STORE_CTX *ctx)
this plugin implements the traditional SSL "wrappermode" streams and STARTTLS extension documented in xmpp-core
static void _sx_ssl_starttls_notify_proceed (sx_t s, void *arg)
static int _sx_ssl_process (sx_t s, sx_plugin_t p, nad_t nad)
static void _sx_ssl_features (sx_t s, sx_plugin_t p, nad_t nad)
static void _sx_ssl_get_external_id (sx_t s, _sx_ssl_conn_t sc)
static int _sx_ssl_handshake (sx_t s, _sx_ssl_conn_t sc)
static int _sx_ssl_wio (sx_t s, sx_plugin_t p, sx_buf_t buf)
static int _sx_ssl_rio (sx_t s, sx_plugin_t p, sx_buf_t buf)
static void _sx_ssl_client (sx_t s, sx_plugin_t p)
static void _sx_ssl_server (sx_t s, sx_plugin_t p)
static void _sx_ssl_free (sx_t s, sx_plugin_t p)
cleanup
static void _sx_ssl_unload (sx_plugin_t p)
int sx_ssl_init (sx_env_t env, sx_plugin_t p, va_list args)
args: name, pemfile, cachain, mode
int sx_ssl_server_addcert (sx_plugin_t p, char *name, char *pemfile, char *cachain, int mode)
args: name, pemfile, cachain, mode
int sx_ssl_client_starttls (sx_plugin_t p, sx_t s, char *pemfile)
Variables
int sx_openssl_initialized = 0
Function Documentation
static int _sx_ssl_verify_callback (int preverify_ok, X509_STORE_CTX * ctx) static
this plugin implements the traditional SSL "wrappermode" streams and STARTTLS extension documented in xmpp-core
Definition at line 31 of file ssl.c.
References _sx_debug, and ZONE.
Referenced by sx_ssl_server_addcert().
static void _sx_ssl_starttls_notify_proceed (sx_t s, void * arg) static
Definition at line 80 of file ssl.c.
References _sx_debug, _sx_reset(), _sx_st::flags, _sx_st::req_to, sx_server_init(), SX_SSL_WRAPPER, and ZONE.
Referenced by _sx_ssl_process().
static int _sx_ssl_process (sx_t s, sx_plugin_t p, nad_t nad) static
Definition at line 99 of file ssl.c.
References _sx_buffer_new(), _sx_debug, _sx_event, _sx_gen_error, _sx_reset(), _sx_ssl_starttls_notify_proceed(), _sx_st::compressed, event_ERROR, _sx_st::flags, _sx_plugin_st::index, jqueue_push(), NAD_ENAME, NAD_ENAME_L, NAD_ENS, nad_free(), NAD_NURI, NAD_NURI_L, _sx_st::ns, _sx_st::plugin_data, _sx_st::req_from, _sx_st::req_to, _sx_st::req_version, _sx_st::ssf, sx_client_init(), SX_ERR_STARTTLS_FAILURE, SX_SSL_STARTTLS_OFFER, SX_SSL_WRAPPER, _sx_st::type, type_CLIENT, type_SERVER, uri_TLS, _sx_st::want_write, _sx_st::wbufq, and ZONE.
Referenced by sx_ssl_init().
static void _sx_ssl_features (sx_t s, sx_plugin_t p, nad_t nad) static
Definition at line 197 of file ssl.c.
References _sx_debug, _sx_st::compressed, _sx_st::flags, nad_add_namespace(), nad_append_elem(), _sx_st::ssf, _sx_st::state, state_STREAM, SX_SSL_STARTTLS_OFFER, SX_SSL_STARTTLS_REQUIRE, uri_TLS, and ZONE.
Referenced by sx_ssl_init().
static void _sx_ssl_get_external_id (sx_t s, _sx_ssl_conn_t sc) static
Definition at line 215 of file ssl.c.
References _sx_debug, SX_CONN_EXTERNAL_ID_MAX_COUNT, and ZONE.
Referenced by _sx_ssl_handshake().
static int _sx_ssl_handshake (sx_t s, _sx_ssl_conn_t sc) static
Definition at line 322 of file ssl.c.
References _sx_debug, _sx_event, _sx_gen_error, _sx_ssl_get_external_id(), event_ERROR, _sx_st::flags, _sx_st::ssf, _sx_st::state, state_STREAM, stream_err_UNDEFINED_CONDITION, sx_close(), SX_ERR_SSL, sx_error(), SX_SSL_WRAPPER, _sx_st::type, type_CLIENT, and ZONE.
Referenced by _sx_ssl_rio(), and _sx_ssl_wio().
static int _sx_ssl_wio (sx_t s, sx_plugin_t p, sx_buf_t buf) static
Definition at line 389 of file ssl.c.
References _sx_buffer_alloc_margin(), _sx_buffer_clear(), _sx_buffer_free(), _sx_buffer_new(), _sx_close(), _sx_debug, _sx_event, _sx_gen_error, _sx_ssl_handshake(), _sx_buf_st::data, event_ERROR, _sx_st::flags, _sx_plugin_st::index, jqueue_pull(), jqueue_push(), jqueue_size(), _sx_buf_st::len, _sx_buf_st::notify, _sx_buf_st::notify_arg, _sx_st::plugin_data, _sx_st::state, state_STREAM, stream_err_UNDEFINED_CONDITION, sx_close(), SX_ERR_SSL, sx_error(), SX_SSL_WRAPPER, _sx_st::want_read, and ZONE.
Referenced by sx_ssl_init().
static int _sx_ssl_rio (sx_t s, sx_plugin_t p, sx_buf_t buf) static
Definition at line 494 of file ssl.c.
References _sx_buffer_alloc_margin(), _sx_buffer_clear(), _sx_close(), _sx_debug, _sx_event, _sx_gen_error, _sx_ssl_handshake(), _sx_buf_st::data, event_ERROR, _sx_st::flags, _sx_plugin_st::index, jqueue_size(), _sx_buf_st::len, _sx_st::plugin_data, _sx_st::state, state_STREAM, stream_err_UNDEFINED_CONDITION, sx_close(), SX_ERR_SSL, sx_error(), SX_SSL_WRAPPER, _sx_st::want_read, _sx_st::want_write, and ZONE.
Referenced by sx_ssl_init().
static void _sx_ssl_client (sx_t s, sx_plugin_t p) static
Definition at line 620 of file ssl.c.
References _sx_chain_io_plugin(), _sx_debug, _sx_st::flags, _sx_plugin_st::index, jqueue_new(), _sx_st::plugin_data, _sx_plugin_st::private, _sx_st::req_from, _sx_st::ssf, SSL_OP_NO_TICKET, SX_CONN_EXTERNAL_ID_MAX_COUNT, SX_SSL_WRAPPER, _sx_st::tag, xhash_get(), and ZONE.
Referenced by sx_ssl_init().
static void _sx_ssl_server (sx_t s, sx_plugin_t p) static
Definition at line 714 of file ssl.c.
References _sx_chain_io_plugin(), _sx_debug, _sx_st::flags, _sx_plugin_st::index, jqueue_new(), _sx_st::plugin_data, _sx_plugin_st::private, _sx_st::req_to, _sx_st::ssf, SX_CONN_EXTERNAL_ID_MAX_COUNT, SX_SSL_WRAPPER, _sx_st::tag, xhash_get(), and ZONE.
Referenced by sx_ssl_init().
static void _sx_ssl_free (sx_t s, sx_plugin_t p) static
cleanup
Definition at line 760 of file ssl.c.
References _sx_buffer_free(), _sx_plugin_st::index, jqueue_free(), jqueue_pull(), log_debug, _sx_st::plugin_data, SX_CONN_EXTERNAL_ID_MAX_COUNT, _sx_st::type, type_NONE, and ZONE.
Referenced by sx_ssl_init().
static void _sx_ssl_unload (sx_plugin_t p) static
Definition at line 797 of file ssl.c.
References _sx_plugin_st::private, xhash_free(), xhash_iter_first(), xhash_iter_get(), and xhash_iter_next().
Referenced by sx_ssl_init().
int sx_ssl_init (sx_env_t env, sx_plugin_t p, va_list args)
args: name, pemfile, cachain, mode
Definition at line 813 of file ssl.c.
References _sx_debug, _sx_ssl_client(), _sx_ssl_features(), _sx_ssl_free(), _sx_ssl_process(), _sx_ssl_rio(), _sx_ssl_server(), _sx_ssl_unload(), _sx_ssl_wio(), _sx_plugin_st::client, _sx_plugin_st::features, _sx_plugin_st::free, _sx_plugin_st::magic, _sx_plugin_st::private, _sx_plugin_st::process, _sx_plugin_st::rio, _sx_plugin_st::server, sx_openssl_initialized, SX_SSL_MAGIC, sx_ssl_server_addcert(), _sx_plugin_st::unload, _sx_plugin_st::wio, and ZONE.
Referenced by _c2s_hosts_expand(), _s2s_hosts_expand(), and JABBER_MAIN().
int sx_ssl_server_addcert (sx_plugin_t p, char * name, char * pemfile, char * cachain, int mode)
args: name, pemfile, cachain, mode
Definition at line 860 of file ssl.c.
References _sx_debug, _sx_ssl_verify_callback(), _sx_plugin_st::private, sx_openssl_initialized, xhash_free(), xhash_get(), xhash_new(), xhash_put(), and ZONE.
Referenced by _c2s_hosts_expand(), _s2s_hosts_expand(), and sx_ssl_init().
int sx_ssl_client_starttls (sx_plugin_t p, sx_t s, char * pemfile)
Definition at line 983 of file ssl.c.
References _sx_buffer_new(), _sx_debug, _sx_event, _sx_st::compressed, event_WANT_WRITE, _sx_plugin_st::index, jqueue_push(), _sx_st::plugin_data, _sx_st::ssf, _sx_st::state, state_STREAM, _sx_st::type, type_CLIENT, uri_TLS, _sx_st::want_write, _sx_st::wbufq, and ZONE.
Referenced by _out_sx_callback(), c2s_router_sx_callback(), s2s_router_sx_callback(), and sm_sx_callback().
Variable Documentation
int sx_openssl_initialized = 0
Definition at line 810 of file ssl.c.
Referenced by sx_ssl_init(), and sx_ssl_server_addcert().