jabberd2: authreg_st Struct Reference
authreg_st Struct Reference
#include <c2s.h>
Data Fields
c2s_t c2s
void * private
module private data
int(* user_exists)(authreg_t ar, char *username, char *realm)
returns 1 if the user exists, 0 if not
int(* get_password)(authreg_t ar, char *username, char *realm, char password[257])
return this users cleartext password in the array (digest auth, password auth)
int(* check_password)(authreg_t ar, char *username, char *realm, char password[257])
check the given password against the stored password, 0 if equal, !0 if not equal (password auth)
int(* set_password)(authreg_t ar, char *username, char *realm, char password[257])
store this password (register)
int(* create_user)(authreg_t ar, char *username, char *realm)
make or break the user (register / register remove)
int(* delete_user)(authreg_t ar, char *username, char *realm)
void(* free)(authreg_t ar)
int(* user_authz_allowed)(authreg_t ar, char *username, char *realm, char *requested_user)
returns 1 if the user is permitted to authorize as the requested_user, 0 if not.
Detailed Description
Definition at line 302 of file c2s.h.
Field Documentation
c2s_t authreg_st::c2s
Definition at line 304 of file c2s.h.
Referenced by authreg_init().
void* authreg_st::private
module private data
Definition at line 307 of file c2s.h.
int(* authreg_st::user_exists)(authreg_t ar, char *username, char *realm)
returns 1 if the user exists, 0 if not
Definition at line 310 of file c2s.h.
Referenced by _authreg_auth_get(), _authreg_auth_set(), _authreg_register_set(), _c2s_sx_sasl_callback(), and authreg_init().
int(* authreg_st::get_password)(authreg_t ar, char *username, char *realm, char password[257])
return this users cleartext password in the array (digest auth, password auth)
Definition at line 313 of file c2s.h.
Referenced by _authreg_auth_get(), _authreg_auth_set(), and _c2s_sx_sasl_callback().
int(* authreg_st::check_password)(authreg_t ar, char *username, char *realm, char password[257])
check the given password against the stored password, 0 if equal, !0 if not equal (password auth)
Definition at line 316 of file c2s.h.
Referenced by _authreg_auth_get(), _authreg_auth_set(), and _c2s_sx_sasl_callback().
int(* authreg_st::set_password)(authreg_t ar, char *username, char *realm, char password[257])
store this password (register)
Definition at line 319 of file c2s.h.
Referenced by _authreg_register_get(), and _authreg_register_set().
int(* authreg_st::create_user)(authreg_t ar, char *username, char *realm)
make or break the user (register / register remove)
Definition at line 322 of file c2s.h.
Referenced by _authreg_register_get(), and _authreg_register_set().
int(* authreg_st::delete_user)(authreg_t ar, char *username, char *realm)
Definition at line 323 of file c2s.h.
Referenced by _authreg_register_set(), and c2s_router_sx_callback().
void(* authreg_st::free)(authreg_t ar)
Definition at line 325 of file c2s.h.
Referenced by authreg_free().
int(* authreg_st::user_authz_allowed)(authreg_t ar, char *username, char *realm, char *requested_user)
returns 1 if the user is permitted to authorize as the requested_user, 0 if not.
requested_user is a JID
Definition at line 330 of file c2s.h.
Referenced by _c2s_sx_sasl_callback().
The documentation for this struct was generated from the following file:
c2s/c2s.h