jabberd2: util/xdata.h File Reference
xdata.h File Reference
#include "util.h"
Data Structures
struct _xdata_st
struct _xdata_field_st
struct _xdata_option_st
struct _xdata_item_st
Typedefs
typedef struct _xdata_st * xdata_t
typedef struct _xdata_field_st * xdata_field_t
typedef struct _xdata_option_st * xdata_option_t
typedef struct _xdata_item_st * xdata_item_t
Enumerations
enum xdata_type_t {
xd_type_NONE, xd_type_FORM, xd_type_RESULT, xd_type_SUBMIT,
xd_type_CANCEL
}
enum xdata_field_type_t {
xd_field_NONE, xd_field_BOOLEAN, xd_field_FIXED, xd_field_HIDDEN,
xd_field_JID_MULTI, xd_field_JID_SINGLE, xd_field_LIST_MULTI, xd_field_LIST_SINGLE,
xd_field_TEXT_MULTI, xd_field_TEXT_PRIVATE, xd_field_TEXT_SINGLE
}
Functions
JABBERD2_API xdata_t xdata_new (xdata_type_t type, char *title, char *instructions)
creation
JABBERD2_API xdata_t xdata_parse (nad_t nad, int root)
parse a nad and build
JABBERD2_API xdata_field_t xdata_field_new (xdata_t xd, xdata_field_type_t type, char *var, char *label, char *desc, int required)
new field
JABBERD2_API xdata_item_t xdata_item_new (xdata_t xd)
new item
JABBERD2_API void xdata_add_field (xdata_t xd, xdata_field_t xdf)
field insertion
JABBERD2_API void xdata_add_rfield (xdata_t xd, xdata_field_t xdf)
JABBERD2_API void xdata_add_field_item (xdata_item_t item, xdata_field_t xdf)
JABBERD2_API void xdata_add_item (xdata_t xd, xdata_item_t xdi)
item insertion
JABBERD2_API void xdata_add_option (xdata_field_t xdf, char *value, int lvalue, char *label, int llabel)
option insertion
JABBERD2_API void xdata_add_value (xdata_field_t xdf, char *value, int vlen)
value insertion
Typedef Documentation
typedef struct _xdata_st* xdata_t
Definition at line 28 of file xdata.h.
typedef struct _xdata_field_st* xdata_field_t
Definition at line 29 of file xdata.h.
typedef struct _xdata_option_st* xdata_option_t
Definition at line 30 of file xdata.h.
typedef struct _xdata_item_st* xdata_item_t
Definition at line 31 of file xdata.h.
Enumeration Type Documentation
enum xdata_type_t
Enumerator:
xd_type_NONE
xd_type_FORM
xd_type_RESULT
xd_type_SUBMIT
xd_type_CANCEL
Definition at line 33 of file xdata.h.
enum xdata_field_type_t
Enumerator:
xd_field_NONE
xd_field_BOOLEAN
xd_field_FIXED
xd_field_HIDDEN
xd_field_JID_MULTI
xd_field_JID_SINGLE
xd_field_LIST_MULTI
xd_field_LIST_SINGLE
xd_field_TEXT_MULTI
xd_field_TEXT_PRIVATE
xd_field_TEXT_SINGLE
Definition at line 55 of file xdata.h.
Function Documentation
JABBERD2_API xdata_t xdata_new (xdata_type_t type, char * title, char * instructions)
creation
Definition at line 26 of file xdata.c.
References _xdata_st::instructions, log_debug, _xdata_st::p, pmalloco(), pool_new, pstrdup(), _xdata_st::title, _xdata_st::type, and ZONE.
Referenced by xdata_parse().
JABBERD2_API xdata_t xdata_parse (nad_t nad, int root)
parse a nad and build
Definition at line 269 of file xdata.c.
References _xdata_field_parse(), nad_st::ecur, _xdata_st::instructions, log_debug, NAD_AVAL, NAD_AVAL_L, NAD_CDATA, NAD_CDATA_L, NAD_ENAME, NAD_ENAME_L, NAD_ENS, nad_find_attr(), nad_find_elem(), NAD_NURI, NAD_NURI_L, _xdata_st::p, pmalloco(), pool_free(), pstrdupx(), _xdata_st::title, _xdata_st::type, uri_XDATA, xd_type_CANCEL, xd_type_FORM, xd_type_NONE, xd_type_RESULT, xd_type_SUBMIT, xdata_add_field(), xdata_new(), and ZONE.
JABBERD2_API xdata_field_t xdata_field_new (xdata_t xd, xdata_field_type_t type, char * var, char * label, char * desc, int required)
new field
Definition at line 49 of file xdata.c.
References _xdata_field_st::desc, _xdata_field_st::label, _xdata_st::p, _xdata_field_st::p, pmalloco(), pstrdup(), _xdata_field_st::required, _xdata_field_st::type, and _xdata_field_st::var.
JABBERD2_API xdata_item_t xdata_item_new (xdata_t xd)
new item
Definition at line 73 of file xdata.c.
References _xdata_st::p, _xdata_item_st::p, and pmalloco().
JABBERD2_API void xdata_add_field (xdata_t xd, xdata_field_t xdf)
field insertion
Definition at line 86 of file xdata.c.
References _xdata_st::fields, _xdata_st::flast, and _xdata_field_st::next.
Referenced by xdata_parse().
JABBERD2_API void xdata_add_rfield (xdata_t xd, xdata_field_t xdf)
Definition at line 98 of file xdata.c.
References _xdata_field_st::next, _xdata_st::rfields, and _xdata_st::rflast.
JABBERD2_API void xdata_add_field_item (xdata_item_t item, xdata_field_t xdf)
Definition at line 110 of file xdata.c.
References _xdata_item_st::fields, _xdata_item_st::flast, and _xdata_field_st::next.
JABBERD2_API void xdata_add_item (xdata_t xd, xdata_item_t xdi)
item insertion
Definition at line 123 of file xdata.c.
References _xdata_st::ilast, _xdata_st::items, and _xdata_item_st::next.
JABBERD2_API void xdata_add_option (xdata_field_t xdf, char * value, int lvalue, char * label, int llabel)
option insertion
JABBERD2_API void xdata_add_value (xdata_field_t xdf, char * value, int vlen)
value insertion
Definition at line 160 of file xdata.c.
References _xdata_field_st::nvalues, _xdata_field_st::p, pool_cleanup(), pstrdupx(), and _xdata_field_st::values.
Referenced by _xdata_field_parse().